# Generated by Django 4.2.15 on 2024-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_book_title', models.CharField(max_length=30)),
                ('topic', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('proposer', models.CharField(max_length=30)),
                ('purchase_link', models.CharField(blank=True, max_length=30, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('offered_at', models.BigIntegerField()),
            ],
        ),
    ]
