# Generated by Django 4.2.15 on 2024-08-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbook',
            name='uid',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
