# Generated by Django 4.2.15 on 2024-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('waiting_for_username', 'waiting_for_username'), ('status_registered', 'status_registered')], default='waiting_for_username', max_length=50)),
            ],
        ),
    ]
