# Generated by Django 4.2.15 on 2024-08-20 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50, null=True)),
                ('step_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='process_uid',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=50)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.process')),
            ],
        ),
    ]
