# Generated by Django 4.2.15 on 2024-08-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_process_contact_process_uid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='process_uid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
