# Generated by Django 4.2.15 on 2024-08-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='borrowed_date',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='return_date',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='borrowed_at',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='due_at',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='return_at',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
